apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-s5yy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-s5yy
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-s5yy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-s5yy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-s5yy
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xtaz-tenant/rhtap-demo-app/hacbs-test-project-s5yy@sha256:58ed8949da550b3d0978ba6af8ed3f8865447a66e19918b0a7adb0f47f6d03a9
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
