apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-s5yy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xtaz-tenant/rhtap-demo-app/hacbs-test-project-s5yy@sha256:926eb9f03b5a513141d50604fbce0b471116e8afc3cbe1ebb5d2508008cc7369
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
