apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-s5yy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xtaz-tenant/rhtap-demo-app/hacbs-test-project-s5yy@sha256:58ed8949da550b3d0978ba6af8ed3f8865447a66e19918b0a7adb0f47f6d03a9
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
